# 2.9 延迟事务

之前，我们在addressbook合约中发送了一个外部内联操作。在本教程中，我们将探讨发送延迟事务，其中包括我们在上一个教程中发送的内联操作。  

## 使用延迟事务替换内联操作。
在您最喜欢的编辑器中打开`addressbook.cpp`文件，并使用以下代码替换`increment_counter`函数。

 ```C++
  void increment_counter(name user, std::string type) {
    eosio::transaction deferred;
    
    deferred.actions.emplace_back(
      permission_level{get_self(),"active"_n},
      get_self(), "notify"_n, 
      std::make_tuple(user, type)
    );

    deferred.send(user.value, get_self());
  }
 ```

上面列出的代码执行以下操作：
 1. 初始化事务对象。
 2. 在上一个`addressbook`示例中创建具有相同参数的操作。
 3. 将action添加到事务中。
 4. 用两个参数发送事务。第一个参数是发送者ID，这在本教程的后面部分中很有用。第二个参数是将支付与延时事务相关的RAM消耗帐户。
 
 
 ## 取消延迟事务

 要取消延迟事务，请使用创建延迟事务时指定的发送者ID调用`cancel_deferred`。在我们的例子中，是user.value。
 如下：
 
 ```
 cancel_deferred(user.value);
 ```
 
 ## 执行延迟事务
 要测试延迟事务是否调用notify action，请运行以下命令：
 ```
 cleos push action addressbook upsert '["alice", "alice", "liddell", 19, "123 drink me way", "wonderland", "amsterdam"]' -p alice@active
 ```
 
 由于事务被延迟，因此即使成功调用了upsert事务，也不会在控制台中看到与延迟事务相关的输出。
 
 ```
 executed transaction: f1143e224c9809aafb6e7274096521168ecfe1e21feb86ca2d4794c4a4929fd5  208 bytes  428 us
 #   addressbook <= addressbook::upsert          {"user":"alice","first_name":"alice","last_name":"liddell","age":19,"street":"123 drink me way","cit...
 warning: transaction executed locally, but may not be confirmed by the network yet         ]
 ```

尽管您不会在控制台中看到延迟的事务输出，但是您可以查看nodeos日志检查事务是否成功执行。要查看nodeos日志，请执行以下命令：
 
 ```
 tail -f nodeos.log
 ```

nodeos.log是在启动nodeos时创建的。
 
 ```
 info  2019-04-08T12:52:34.000 thread-0  producer_plugin.cpp:1596      produce_block        ] Produced block 00081d73bfb74c06... #531827 @ 2019-04-08T12:52:34.000 signed by eosio [trxs: 0, lib: 531826, confirmed: 0]
 
 info  2019-04-08T12:52:34.502 thread-0  producer_plugin.cpp:1596      produce_block        ] Produced block 00081d7447279fcf... #531828 @ 2019-04-08T12:52:34.500 signed by eosio [trxs: 1, lib: 531827, confirmed: 0]
 info  2019-04-08T12:52:35.004 thread-0  producer_plugin.cpp:1596      produce_block        ] Produced block 00081d758add241e... #531829 @ 2019-04-08T12:52:35.000 signed by eosio [trxs: 1, lib: 531828, confirmed: 0]
 
 info  2019-04-08T12:52:35.503 thread-0  producer_plugin.cpp:1596      produce_block        ] Produced block 00081d76113974b9... #531830 @ 2019-04-08T12:52:35.500 signed by eosio [trxs: 0, lib: 531829, confirmed: 0]
 
 ```
 
 您可以看到有两个事务（trx）连续执行。这意味着延时事务是由nodeos执行的。
 
 ## 小心点出错
 
 当合约代码引发异常时，可以使用错误处理代码来处理。您可以定义自己的错误处理代码，如下所示：
 
 
  ```
 void onError() {
    print("onError is called");
 }
 ```
 
附带以下notify属性：
 
 ```
 [[eosio::on_notify("eosio::onerror")]]
 void onError() {
    print("onError is called");
 }
 ```
 
 使用上面的onError函数，您可以处理各种异常。这允许您在必要时安全的失败。  
 
 有关OnError内部工作方式的更多详细信息，请参阅[此处](https://developers.eos.io/eosio-nodeos/v1.7.0/docs/communication-model) 
 
 
## 非确定性
 
 因为您可以在将来的某个时间点调度延迟事务，所以延迟事务的执行是不确定的。  
 可能是EOSIO网络上的任何节点都不会尝试执行计划的延迟事务。由于EOSIO区块链网络的所有用户都可以安排延迟事务，因此待执行的事务可以累积到backlog中。在计划执行延迟事务之前，可能已达到延迟事务的过期时间。  
 由于这种行为和其他主观原因，您不应该基于延迟事务的确定性执行来设计应用程序。  
 有关延迟事务如何工作的更多详细信息，请参见[此处](https://developers.eos.io/eosio-nodeos/v1.7.0/docs/communication-model)  
 







